name: 'Bicep Infrastructure Apply'

on:
  workflow_dispatch:  
    branches:
    - main
  push:
    branches:
    - main

jobs:
  bicep:
    name: 'Bicep'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/tenant

    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Bicep
      run: az bicep install

    - name: Bicep Build
      id: build
      run: az bicep build --file main.bicep

    - name: Bicep Deploy
      id: deploy
      run: az deployment group create --resource-group crgar-aca-dev-tenant-rg --template-file main.json --parameters @parameters.json
