name: 'Bicep Infrastructure Plan'

on:
  workflow_dispatch:  
    branches:
    - main
  pull_request:
    # paths:
    # - infra/tenant

jobs:
  bicep:
    name: 'Bicep'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/tenant

    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Bicep
      run: az bicep install

    - name: Bicep Build
      id: build
      run: az bicep build --file main.bicep

    - name: Bicep Plan
      id: plan
      run: az deployment group what-if --resource-group crgar-aca-dev-tenant-rg --template-file main.json --parameters @parameters.json

    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "bicep\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Bicep Build 🖌\`${{ steps.build.outcome }}\`
          #### Bicep Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
